
import java.awt.Color;
import java.awt.Font;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Scanner;
import java.util.logging.Logger;
import javax.swing.JPanel;
import sun.rmi.runtime.Log;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stephane
 */
public class Tanque extends javax.swing.JFrame {
String serverIP;
boolean inicia=false;
int serverPort;
private volatile Thread runner;
int freqDiaria;
String periodo[];
String dataInicial="";
String deslPeriodos="";
String periodos="";
int avanco=0; //avanço de dias (+)

 JPanel verde = new JPanel(); 
    /**
     * Creates new form Tanque
     */
    public Tanque(String dispositivo, String porta, int[] quantDias, String dataInicial,int freqDiaria,double[] deslProt){
        initComponents();
       serverIP=dispositivo;
       
       for(int i=0;i<9;i++)
       {
          
       deslPeriodos+=deslProt[i]+"#";  
       periodos+=quantDias[i]+"#"; 
     
       }
       
      
       this.freqDiaria=freqDiaria;
       this.dataInicial=dataInicial;
       serverPort=Integer.parseInt(porta);
       jLabel2.setFont(new Font("Courier", Font.BOLD + Font.ITALIC, 20));
       enviar.setFont(new Font("Courier", Font.BOLD + Font.ITALIC, 14));
       jLabel1.setFont(new Font("Courier", Font.BOLD + Font.ITALIC, 14));
       jLabel3.setFont(new Font("Courier", Font.BOLD + Font.ITALIC, 14));
       jLabel4.setFont(new Font("Courier", Font.BOLD + Font.ITALIC, 14));
       jLabel11.setFont(new Font("Courier", Font.BOLD + Font.ITALIC, 14));
                  
       if(freqDiaria!=0)
       {
       numeroAlimentacoes.setVisible(false);
       jLabel4.setVisible(false);
       }
       caixa9.setText("Data inicial de alimentação: "+dataInicial);
     if (runner != null) 
        return;
    
    runner = new Thread(this::funcloop);
    runner.start();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        NVA = new javax.swing.JLabel();
        hUA = new javax.swing.JLabel();
        hIA = new javax.swing.JLabel();
        hFA = new javax.swing.JLabel();
        hPA = new javax.swing.JLabel();
        caixaHIA = new javax.swing.JLabel();
        caixa1 = new javax.swing.JLabel();
        caixa2 = new javax.swing.JLabel();
        caixa3 = new javax.swing.JLabel();
        caixa4 = new javax.swing.JLabel();
        caixa5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        caixa6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        hULeitura = new javax.swing.JLabel();
        caixa7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        caixa9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        caixa11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        horarioInicial = new javax.swing.JFormattedTextField();
        horarioFinal = new javax.swing.JFormattedTextField();
        numeroAlimentacoes = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Horario Inicial de alimentação: ");

        jLabel3.setText("Horario Final de alimentação: ");

        jLabel4.setText("Número de alimentações:");

        enviar.setBackground(new java.awt.Color(23, 84, 247));
        enviar.setText("Enviar dados");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\stephane\\Desktop\\Projeto Psicultura\\Figuras\\img1.jpg")); // NOI18N

        NVA.setText("Número de vezes que já alimentou: ");

        hUA.setText("Horário da última alimentação: ");

        hIA.setText("Horário Inicial de Alimentação:");

        hFA.setText("Horário Final de alimentação:");

        hPA.setText("Horário da próxima alimentação:");

        jLabel6.setText("Número de alimentações ao longo do dia:");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        hULeitura.setText("Horário da última leitura:");

        jLabel7.setText("Periodo de alimentação:");

        jLabel8.setText("Dias que faltam alimentar:");

        caixa9.setText("Data inicial de alimentação:");

        jLabel11.setText("Cardume  de tilápias");

        caixa11.setText("Data atual:");

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setText("Acrescentar um dia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(23, 84, 247));

        try {
            horarioInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horarioInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioInicialActionPerformed(evt);
            }
        });

        try {
            horarioFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            numeroAlimentacoes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(numeroAlimentacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(horarioFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(horarioInicial, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(horarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(horarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numeroAlimentacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caixa6)
                                .addContainerGap(476, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(enviar))
                                    .addComponent(jButton2))
                                .addGap(23, 23, 23))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(hULeitura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(caixa7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addComponent(caixaHIA))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel11)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(caixa9))
                                            .addComponent(jLabel8)
                                            .addComponent(caixa11)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NVA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caixa5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hFA)
                                    .addComponent(hUA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caixa3)
                                    .addComponent(caixa2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caixa4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hIA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(caixa1)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4)))
                        .addGap(71, 71, 71)
                        .addComponent(caixaHIA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caixa7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hULeitura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hIA)
                                    .addComponent(caixa1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(caixa9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hFA)
                            .addComponent(caixa2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hUA)
                            .addComponent(caixa3)
                            .addComponent(caixa11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hPA)
                            .addComponent(caixa4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NVA)
                            .addComponent(caixa5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(caixa6))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enviar)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(23, 84, 247));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanque 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
       
        System.out.println("\n\nDeslocamento do Protótipo: "+deslPeriodos);    
       System.out.println("Quant dias: "+periodos);   
     
           
        String hInicial=horarioInicial.getText();
        String vetHInicial[] = hInicial.split(":");
        int tempoInicial =(Integer.parseInt(vetHInicial[0])*3600) +(Integer.parseInt(vetHInicial[1])*60);

        String hFinal=horarioFinal.getText();
        String vetHFinal[] = hFinal.split(":");
        int tempoFinal =(Integer.parseInt(vetHFinal[0])*3600) +(Integer.parseInt(vetHFinal[1])*60);
        System.out.println("Min Final: "+Integer.parseInt(vetHFinal[1])*60);
        String pacote;
        if(freqDiaria!=0) // modo manual
       {
    //  pacote=tempoInicial+","+tempoFinal+","+freqDiaria;
      pacote=tempoInicial+","+tempoFinal+","+freqDiaria+","+dataInicial+","+periodos+","+deslPeriodos+","+avanco;
       avanco=0;
        }
        else{   // modo automático
      // pacote=tempoInicial+","+tempoFinal+","+numeroAlimentacoes.getText();
      System.out.println("Data Inicial: "+dataInicial);
     pacote=tempoInicial+","+tempoFinal+","+numeroAlimentacoes.getText()+","+dataInicial+","+periodos+","+0+","+avanco;
     avanco=0; 
     System.out.println("Periodos: "+periodos);
       System.out.println("Deslocamentos: "+deslPeriodos);
        }
        System.out.println("TempoInicial: "+tempoInicial);
        System.out.println("TempoFinal: "+tempoFinal);
         System.out.println("Pacote: "+pacote);

        try {
            System.out.println("\nPacote:"+pacote);
            ClasseSocket(pacote, serverIP, serverPort);
        } catch (IOException ex) {
            Logger.getLogger(Tanque.class.getName()).log(Level.SEVERE, null, ex);
       
        } catch (InterruptedException ex) {
           //   
            Logger.getLogger(Tanque.class.getName()).log(Level.SEVERE, null, ex);
        
        }

    }//GEN-LAST:event_enviarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Tanques t = new Tanques();
    t.setVisible(true);
    dispose();    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        avanco=1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void horarioInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioInicialActionPerformed

  private void funcloop() {
    while (runner == Thread.currentThread()) {
       
        try {
            ClasseSocket("pacote", serverIP, serverPort);
            Thread.currentThread().sleep(100);  
        } catch (IOException ex) {
            Logger.getLogger(Tanque.class.getName()).log(Level.SEVERE, null, ex);
          
        } catch (InterruptedException ex) {
            Logger.getLogger(Tanque.class.getName()).log(Level.SEVERE, null, ex);
       
      
        }
    }
}
    
    
    public void mensagemRecebida(String mensagem) 
    {          
        
   DecimalFormat df =  new DecimalFormat("0");
   String message[] = mensagem.split(",");
 
   int NAlimentacoes=Integer.parseInt(message[7]);
     
  if(NAlimentacoes==0) {
   System.out.println("Mensagem nula");}
  else{
   
 caixa7.setText(message[1]);
   
    float hInicialR=Float.parseFloat(message[2])/3600;
  int hIR=(int) hInicialR;
   float hIRR=(hInicialR-hIR)*60;
   if(hIRR<10) { caixa1.setText(hIR+":0"+df.format(hIRR));   } 
   else{ caixa1.setText(hIR+":"+df.format(hIRR)); }
   
   
   float hFinalR=Float.parseFloat(message[3])/3600;
   int hFR= (int) hFinalR;
   float hFRR=(hFinalR-hFR)*60;
  if(hFRR<10) { caixa2.setText(hFR+":0"+df.format(hFRR));   } 
   else{ caixa2.setText(hFR+":"+df.format(hFRR)); }
   
    float hUltimaAR=Float.parseFloat(message[4])/3600;
   int hUAR= (int) hUltimaAR;
   float hUARR=(hUltimaAR-hUAR)*60;
  if(hUARR<10) { caixa3.setText(hUAR+":0"+df.format(hUARR));   } 
   else{   caixa3.setText(hUAR+":"+df.format(hUARR)); }
   
   float hProxAR=Float.parseFloat(message[5])/3600;
   int hPAR= (int) hProxAR;
   float hPARR=(hProxAR-hPAR)*60;
   if(hProxAR>hFinalR)
   {
   caixa4.setText("Período de alimentação completo!");    
   }
      
   else{
  if(hPARR<10) { caixa4.setText(hPAR+":0"+df.format(hPARR));   } 
   else{   caixa4.setText(hPAR+":"+df.format(hPARR)); }
   }
   
    int Nvezes=Integer.parseInt(message[6]);
    caixa5.setText(""+Nvezes);
   

    caixa6.setText(""+NAlimentacoes);
    
    
   System.out.println(""+mensagem);
  caixa11.setText("Data atual: "+message[8]);
   
   
    int diasQueFaltam=Integer.parseInt(message[9]);
    jLabel8.setText("Dias que faltam alimentar: "+diasQueFaltam);
   
   
    int periodoTotal=Integer.parseInt(message[10]);
       jLabel7.setText("Periodo de alimentação: "+periodoTotal); 
   
   
    }
    }
     public void ClasseSocket(String pacote, String serverIP, int serverPort) throws IOException, InterruptedException
            {
               
		  String msgToServer;//Message that will be sent to Arduino
		  String msgFromServer;//recieved message will be stored here
		  java.net.Socket clientSocket = new java.net.Socket(serverIP, serverPort);//making the socket connection
		  System.out.println("Connectado com: "+serverIP+" na porta: "+serverPort);//debug
                //  Thread.sleep(1);
		  DataOutputStream outToServer = new DataOutputStream(clientSocket.getOutputStream());
	      DataInputStream inFromServer = new DataInputStream(clientSocket.getInputStream());//testing DataInputStream
                  outToServer.writeBytes(pacote);  
  
                  String mensagem=inFromServer.readLine();
                  
                 System.out.println("Mensagem: "+mensagem);
               if(mensagem==null)    
               {
                 System.out.println("¨¨¨¨¨¨Mensagem: "+mensagem);
               
               }
               else{ String leitura[] = mensagem.split(",");
                  if(leitura[0].equals("L"))
                  {
                  mensagemRecebida(mensagem);
                  }
                  else{
                  System.out.println("Mensagem recebida: " + mensagem);//print the answer
                          }
               }
                
         }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
        }});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NVA;
    private javax.swing.JLabel caixa1;
    private javax.swing.JLabel caixa11;
    private javax.swing.JLabel caixa2;
    private javax.swing.JLabel caixa3;
    private javax.swing.JLabel caixa4;
    private javax.swing.JLabel caixa5;
    private javax.swing.JLabel caixa6;
    private javax.swing.JLabel caixa7;
    private javax.swing.JLabel caixa9;
    private javax.swing.JLabel caixaHIA;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel hFA;
    private javax.swing.JLabel hIA;
    private javax.swing.JLabel hPA;
    private javax.swing.JLabel hUA;
    private javax.swing.JLabel hULeitura;
    private javax.swing.JFormattedTextField horarioFinal;
    private javax.swing.JFormattedTextField horarioInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField numeroAlimentacoes;
    // End of variables declaration//GEN-END:variables

    private Tanque() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
